find_path(GSASL_INCLUDE_DIRS NAMES gsasl.h PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include" NO_DEFAULT_PATH)
find_library(GSASL_LIBRARIES NAMES gsasl PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib" NO_DEFAULT_PATH)
if(NOT GSASL_INCLUDE_DIRS OR NOT GSASL_LIBRARIES)
    message(FATAL_ERROR "Broken installation of vcpkg port gsasl")
endif()
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GSASL DEFAULT_MSG GSASL_LIBRARIES GSASL_INCLUDE_DIRS)

MARK_AS_ADVANCED(GSASL_LIBRARIES GSASL_INCLUDE_DIRS)

message("*** GSASL_LIBRARIES: ${GSASL_LIBRARIES} **")
message("*** GSASL_INCLUDE_DIRS: ${GSASL_INCLUDE_DIRS} **")